"use client";

import { X } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { EmptyState } from "@/components/dashboard/EmptyState";
import { LoadingSkeleton } from "@/components/dashboard/LoadingSkeleton";
import { Button } from "@/components/ui/button";
import { fetchInventoryLedger, type InventoryLedgerEntry } from "@/services/inventory";
import type { ProductItem } from "@/types/marketplace";

const formatDate = (value?: string) => value ? new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "Not available";

export function InventoryLedgerDrawer({ product, onClose }: { product: ProductItem; onClose: () => void }) {
  const ledgerQuery = useQuery<InventoryLedgerEntry[], Error>({ queryKey: ["inventory-ledger", product.productId], queryFn: () => fetchInventoryLedger(product.productId ?? ""), enabled: Boolean(product.productId), staleTime: 1000 * 30 });
  const entries = [...(ledgerQuery.data ?? [])].sort((first, second) => (second.createdAt ?? "").localeCompare(first.createdAt ?? ""));

  return <><button type="button" aria-label="Close inventory history" className="fixed inset-0 z-40 bg-stone-950/50" onClick={onClose} /><aside className="fixed inset-x-0 bottom-0 z-50 max-h-[92vh] overflow-y-auto rounded-t-2xl border border-stone-200 bg-stone-50 p-5 shadow-2xl dark:border-stone-800 dark:bg-stone-950 sm:inset-y-0 sm:right-0 sm:left-auto sm:h-full sm:w-[min(100%,42rem)] sm:rounded-none sm:border-y-0 sm:border-r-0" role="dialog" aria-modal="true" aria-labelledby="inventory-ledger-title"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-emerald-600">Inventory history</p><h2 id="inventory-ledger-title" className="mt-2 text-xl font-semibold text-stone-900 dark:text-stone-50">{product.name}</h2><p className="mt-1 text-sm text-stone-500">SKU: {product.sku ?? "Not available"}</p></div><Button type="button" variant="ghost" size="icon" onClick={onClose} aria-label="Close inventory history"><X className="h-5 w-5" /></Button></div>{ledgerQuery.isLoading ? <div className="mt-6"><LoadingSkeleton rows={5} /></div> : null}{ledgerQuery.isError ? <div className="mt-6 space-y-3"><EmptyState title="Unable to load inventory history" description={ledgerQuery.error.message} /><Button type="button" variant="outline" onClick={() => ledgerQuery.refetch()}>Retry</Button></div> : null}{!ledgerQuery.isLoading && !ledgerQuery.isError && entries.length === 0 ? <div className="mt-6"><EmptyState title="No inventory history" description="Movement history will appear when stock changes are recorded." /></div> : null}{!ledgerQuery.isLoading && !ledgerQuery.isError && entries.length > 0 ? <div className="mt-6 overflow-x-auto"><table className="min-w-[40rem] w-full text-left text-xs"><thead className="text-stone-500"><tr><th className="px-2 py-2">Date</th><th className="px-2 py-2">Movement</th><th className="px-2 py-2">Change</th><th className="px-2 py-2">Previous</th><th className="px-2 py-2">New</th><th className="px-2 py-2">Reference</th></tr></thead><tbody className="divide-y divide-stone-200 dark:divide-stone-800">{entries.map((entry, index) => <tr key={entry.ledgerId ?? `${entry.createdAt}-${index}`}><td className="px-2 py-3 whitespace-nowrap">{formatDate(entry.createdAt)}</td><td className="px-2 py-3">{entry.movementType ?? "Not available"}</td><td className="px-2 py-3 font-semibold">{entry.quantityChange ?? 0}</td><td className="px-2 py-3">{entry.previousQuantity ?? 0}</td><td className="px-2 py-3">{entry.newQuantity ?? 0}</td><td className="px-2 py-3">{entry.referenceType ?? "Manual"}{entry.referenceId ? ` / ${entry.referenceId}` : ""}</td></tr>)}</tbody></table></div> : null}</aside></>;
}