import Link from "next/link";
import type { OfferItem } from "@/services/promotions";

const money = (value: number) => `₹${value.toLocaleString("en-IN")}`;
const expiry = (value: string) => new Date(value).toLocaleDateString("en-IN", { day: "numeric", month: "short" });

export function PromotionOfferCard({ offer, categoryLookup }: { offer: OfferItem; categoryLookup?: Map<string, { categoryId: string; name?: string; slug?: string }> }) {
  const categoryIds = offer.categoryIds ?? [];
  return <article className="overflow-hidden rounded-[1.75rem] border border-stone-200 bg-white shadow-sm dark:border-stone-800 dark:bg-zinc-900"><div className="h-48 bg-stone-100 dark:bg-stone-800">{offer.bannerImage ? <img src={offer.bannerImage} alt={offer.title} className="h-full w-full object-cover" /> : null}</div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-600">{offer.festivalName}</p><h3 className="mt-2 text-xl font-semibold text-stone-900 dark:text-stone-50">{offer.title}</h3></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-sm font-semibold text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300">{offer.discountType === "percentage" ? `${offer.discountValue}% off` : `${money(offer.discountValue)} off`}</span></div><div className="mt-4 flex flex-wrap gap-2">{categoryIds.length ? categoryIds.map((categoryId) => { const category = categoryLookup?.get(categoryId); return <Link key={categoryId} href={category ? `/category/${category.categoryId ?? category.slug}` : "/categories"} className="cursor-pointer rounded-full bg-stone-100 px-2.5 py-1 text-xs text-stone-600 transition hover:scale-105 hover:bg-emerald-100 hover:text-emerald-700 dark:bg-stone-800 dark:text-stone-300 dark:hover:bg-emerald-950/60 dark:hover:text-emerald-300">{category?.name ?? "Unknown Category"}</Link>; }) : <span className="rounded-full bg-stone-100 px-2.5 py-1 text-xs text-stone-600 dark:bg-stone-800 dark:text-stone-300">All categories</span>}</div><p className="mt-4 text-xs text-stone-500 dark:text-stone-400">Valid until {expiry(offer.endsAt)}</p></div></article>;
}
