"use client";

import { useState } from "react";
import type { AddressItem, CreateAddressPayload } from "@/services/addresses";

const blank: CreateAddressPayload = { fullName: "", mobile: "", house: "", street: "", landmark: "", city: "", state: "", pincode: "", addressType: "home", isDefault: false };

export function AddAddressSheet({ address, onClose, onSave, saving }: { address?: AddressItem | null; onClose: () => void; onSave: (payload: CreateAddressPayload) => void; saving: boolean }) {
  const [form, setForm] = useState<CreateAddressPayload>(address ? { ...blank, ...address } : blank);
  const set = (key: keyof CreateAddressPayload, value: string | boolean | number | undefined) => setForm((current) => ({ ...current, [key]: value }));
  if (!address && !onClose) return null;
  const fields: Array<[keyof CreateAddressPayload, string]> = [["fullName", "Receiver name"], ["mobile", "Phone number"], ["house", "House / flat"], ["street", "Street / area"], ["landmark", "Landmark"], ["city", "City"], ["state", "State"], ["pincode", "Pincode"], ["latitude", "Latitude (optional)"], ["longitude", "Longitude (optional)"]];
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-stone-950/50 p-0 sm:items-center sm:p-6" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl bg-white p-6 dark:bg-stone-900 sm:rounded-3xl"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{address ? "Edit address" : "Add address"}</h2><button type="button" onClick={onClose} className="text-sm font-semibold text-stone-500">Close</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{fields.map(([key, label]) => <label key={key} className="space-y-1.5 text-sm font-medium text-stone-700 dark:text-stone-300"><span>{label}</span><input type={key === "latitude" || key === "longitude" ? "number" : "text"} required={key !== "landmark" && key !== "latitude" && key !== "longitude"} value={String(form[key] ?? "")} onChange={(event) => set(key, key === "latitude" || key === "longitude" ? (event.target.value ? Number(event.target.value) : undefined) : event.target.value)} className="min-h-10 w-full rounded-lg border border-stone-200 bg-white px-3 text-sm outline-none focus:border-emerald-500 dark:border-stone-800 dark:bg-stone-950" /></label>)}</div><div className="mt-4 flex flex-wrap items-center gap-4"><label className="text-sm"><span className="mr-2">Type</span><select value={form.addressType ?? "home"} onChange={(event) => set("addressType", event.target.value)} className="rounded-lg border border-stone-200 bg-white px-3 py-2 dark:border-stone-800 dark:bg-stone-950"><option value="home">Home</option><option value="work">Work</option><option value="other">Other</option></select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isDefault ?? false} onChange={(event) => set("isDefault", event.target.checked)} />Default address</label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border border-stone-200 px-4 py-2 text-sm font-semibold dark:border-stone-700">Cancel</button><button type="button" disabled={saving} onClick={() => onSave(form)} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Saving..." : "Save address"}</button></div></div></div>;
}
